### ISSUE TITLE
Node beginner 

### ISSUE THREAD

**Issue by Dbest904** [15Dkatz/sf-chain-guides#1]
The course instructions said 
With Node installed, you should get responses similar to this on the command line:

$ node -v

v8.8.1 (or something similar)

Im getting 
> $ node -v
$ node -v
  ^^^^

SyntaxError: Unexpected identifier

**Comment by Dbest904** [comment]
How do I Fix

**Comment by 15Dkatz** [comment]
Don't type in the $. That is the prompt itself.
